// Generated by scripts/exercises-prune.mjs — do not edit.
//
// The browser-safe half of the catalogue: the generation stamp and the URL shape, and
// nothing else. `src/lib/exercises/` is Worker-only (~650 KB of prose), so a component
// that wants a thumbnail imports this instead — the boundary is enforced by
// `test/unit/exercises.test.ts`, because tsc cannot see it.

/** The catalogue generation. Also the R2 prefix every mirrored image lives under, which is
 *  what makes the year-long immutable cache on those URLs honest: bytes under a successful
 *  URL never change, and a re-vendored catalogue moves every URL at once. */
export const CATALOG_VERSION = 'fe878dc7'

/** How many exercises this generation ships. */
export const CATALOG_COUNT = 571

/**
 * The app URL for one illustration. `card` is the alias the UI uses when it does not know
 * which poses an exercise has — a session payload carries names and ids, never poses — and
 * the route resolves it server-side to `peak` where there is one and `main` otherwise.
 */
export const exerciseImageUrl = (
  exerciseId: string,
  pose: 'card' | 'start' | 'peak' | 'main' = 'card',
): string => `/api/exercises/img/${CATALOG_VERSION}/${exerciseId}/${pose}.webp`
