/**
 * Drizzle schema — the source of truth for D1. Regenerate migrations with `pnpm db:generate`.
 *
 * Scope is deliberately small: one athlete, one 22-week block starting 24 Aug 2026.
 * That is ~130 activities by race day, which is why there is no outbox, no tombstone
 * table, no materialised training-load table and no multi-user plumbing — everything
 * derived is cheap enough to compute on read.
 */
import { sql } from 'drizzle-orm'
import { index, integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core'

const now = sql`(unixepoch() * 1000)`

/**
 * Activities inside the training block. Nothing before `BLOCK_START` is synced — the
 * 2020–2026 history lives in docs/data/*.csv, where the analysis that needed it already
 * happened.
 *
 * Units follow Strava exactly (metres, seconds, m/s) so sync never converts; paces are
 * derived at read time.
 */
export const activities = sqliteTable(
  'activities',
  {
    id: integer('id').primaryKey(), // Strava activity id
    name: text('name').notNull(),
    sportType: text('sport_type').notNull(),
    /** Local wall clock, epoch ms — "which day was this run", independent of viewer. */
    startedOn: integer('started_on').notNull(),
    distanceM: real('distance_m').notNull(),
    movingS: integer('moving_s').notNull(),
    elevationGainM: real('elevation_gain_m'),
    averageHeartrate: real('average_heartrate'),
    maxHeartrate: real('max_heartrate'),
    /** Steps per minute — already doubled from Strava's rpm. The knee-protocol marker. */
    cadenceSpm: integer('cadence_spm'),
    sufferScore: integer('suffer_score'),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [index('idx_activities_date').on(t.startedOn)],
)

export const SESSION_TYPES = [
  'easy',
  'long',
  'tempo',
  'interval',
  'race',
  'rest',
  'cross',
  'strength',
] as const
export type SessionType = (typeof SESSION_TYPES)[number]

/**
 * The training plan, one row per prescribed session. Generated by
 * `src/lib/training/plan.ts` from docs/03-training-plan-2027.md and re-seedable at will.
 */
export const planSessions = sqliteTable(
  'plan_sessions',
  {
    id: text('id').primaryKey(), // `w03-tue` — stable, so re-seeding updates in place
    weekIndex: integer('week_index').notNull(), // 0-based from block start
    scheduledOn: integer('scheduled_on').notNull(), // local date at 00:00, epoch ms
    type: text('type', { enum: SESSION_TYPES }).notNull(),
    title: text('title').notNull(),
    notes: text('notes'),
    targetDistanceM: real('target_distance_m'),
    targetPaceLoSKm: real('target_pace_lo_s_km'), // faster bound
    targetPaceHiSKm: real('target_pace_hi_s_km'), // slower bound
    /** Marked done by hand, or matched to an activity on read. */
    doneAt: integer('done_at'),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [index('idx_sessions_date').on(t.scheduledOn)],
)

/**
 * Single-row key/value store. Holds the Strava refresh token (AES-GCM encrypted) and the
 * last-sync cursor — a whole table each would be ceremony for two values.
 */
export const appState = sqliteTable('app_state', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
  updatedAt: integer('updated_at').notNull().default(now),
})

export type Activity = typeof activities.$inferSelect
export type NewActivity = typeof activities.$inferInsert
export type PlanSession = typeof planSessions.$inferSelect
export type NewPlanSession = typeof planSessions.$inferInsert
