import raw from './catalog.json?raw'

/**
 * The exercise catalogue: 571 illustrated moves, vendored from RepDB.
 *
 * ## Why it is a file and not a table
 *
 * Nothing in this app ever writes an exercise, and every athlete reads the same rows. A
 * `exercises` table in D1 would be a second copy of a finished third-party record with a
 * sync problem attached — which is the argument `baseline.ts` already makes about last
 * season's CSVs, and the reason AGENTS.md's "no more tables" rule is about *derived* data
 * rather than about tables in general. So the catalogue is generated by
 * `scripts/exercises-prune.mjs`, committed, and read here: one artifact, one version, and
 * "which catalogue is this deployment running" has exactly one answer.
 *
 * Read `?raw` and parsed, the `baseline.ts` way (AGENTS gotcha 14 — Vite inlines it in the
 * Worker bundle, in the prerender pass and in vitest alike). `?raw` rather than a plain
 * JSON import because a 651 KB literal is a type TypeScript would have to build and hold
 * on every check, for no benefit: the shape is `CatalogExercise` and it is asserted once,
 * here, at the boundary.
 *
 * ## This directory is Worker-only
 *
 * The parsed catalogue is ~650 KB of Spanish prose. It must never ride into the client
 * bundle — the whole app is a few tens of KB — so **nothing under `src/components/` and
 * nothing browser-shipped may import `src/lib/exercises/`**. A component that wants a
 * thumbnail URL imports `src/lib/exercise-meta.ts` (generated, tiny); a screen that wants
 * to search calls `GET /api/exercises`. `tsc` cannot see that boundary any more than it
 * could see the router/pages join, so `test/unit/exercises.test.ts` reads the source and
 * fails on the import — the `nav.test.ts` shape.
 *
 * Pure by the house definition: no bindings, no clock, no drizzle, no zod.
 *
 * ## Licence
 *
 * RepDB Free Tier v1.0 (`LICENSE.md` beside this file). Attribution is required and
 * visible — README, `/plantillas` and the exercise picker all carry it. Redistribution
 * *as a dataset* is not permitted, which is why `GET /api/exercises` is a capped, trimmed,
 * signed-in search box and never a dump.
 */

/** One vendored exercise — exactly the projection `exercises-prune.mjs` writes. */
export interface CatalogExercise {
  /** RepDB's own slug, e.g. `single-leg-glute-bridge`. Stable across releases. */
  id: string
  /** Spanish, and the name a prescription copies when the athlete picks this row. */
  name: string
  /** English. Shipped for one reader: an agent searching over MCP queries in English. */
  nameEn: string
  description: string
  instructions: string[]
  tips: string[]
  category: string
  bodyPart: string
  difficulty: string
  /** `null` *is* bodyweight — the source's `is_bodyweight` flag is exactly this, so it is
   *  derived rather than stored twice (the prune script asserts the biconditional). */
  equipment: string | null
  primaryMuscles: string[]
  secondaryMuscles: string[]
  /** Facets the knee protocol cares about live here: `knee_safe`, `no_axial_load`, `rehab`. */
  tags: string[]
  isUnilateral: boolean
  /** Which illustrations exist: `['start','peak']` for a movement, `['main']` for a hold. */
  poses: string[]
}

interface CatalogFile {
  version: string
  count: number
  sourceSha256: string
  exercises: CatalogExercise[]
}

const catalog = JSON.parse(raw) as CatalogFile

/** The generation stamp. `src/lib/exercise-meta.ts` carries the same string for the
 *  browser; `test/unit/exercises.test.ts` fails if the two ever disagree. */
export const CATALOG_VERSION = catalog.version

/** sha256 of the RepDB `exercises.json` this was projected from — `exercises-populate.mjs`
 *  checks it so images and metadata can only ever come from one snapshot. */
export const CATALOG_SOURCE_SHA256 = catalog.sourceSha256

export const EXERCISES: readonly CatalogExercise[] = catalog.exercises

const BY_ID = new Map(EXERCISES.map((exercise) => [exercise.id, exercise]))

export const exerciseById = (id: string): CatalogExercise | undefined => BY_ID.get(id)

/**
 * The vocabularies, derived from the rows rather than typed a second time.
 *
 * They are what the search endpoint validates a facet against — a typo'd `muscle=glutes`
 * comes back as a 400 naming the field instead of an empty result set that reads like "no
 * such exercise" — and what `exercise-labels.ts` is checked for completeness against.
 */
const vocabulary = (of: (exercise: CatalogExercise) => string[]): string[] =>
  [...new Set(EXERCISES.flatMap(of))].sort()

export const MUSCLES = vocabulary((e) => [...e.primaryMuscles, ...e.secondaryMuscles])
export const TAGS = vocabulary((e) => e.tags)
export const EQUIPMENT = vocabulary((e) => (e.equipment ? [e.equipment] : []))
export const BODY_PARTS = vocabulary((e) => [e.bodyPart])
export const CATEGORIES = vocabulary((e) => [e.category])
export const DIFFICULTIES = vocabulary((e) => [e.difficulty])

/**
 * Case- and diacritic-insensitive, and separator-insensitive with it.
 *
 * Three things are being matched against each other here and all three punctuate
 * differently: a Spanish name («Sentadilla Búlgara»), an English one ("Bulgarian Split
 * Squat") and a slug (`bulgarian-split-squat`). Folding every run of non-alphanumerics to
 * a single space puts all three in the same alphabet, which is what lets "side plank" find
 * `side-plank` and "sentadilla" find «Sentadilla». NFD then dropping the combining marks
 * is the cheap accent fold — no `Intl.Collator`, no locale data, and it is exactly right
 * for the five vowels and the eñe that Spanish needs here.
 */
const fold = (text: string): string =>
  text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()

/** Lower is better: a prefix beats a word start beats a substring. `null` is no match. */
function rankIn(haystack: string, needle: string): number | null {
  const at = haystack.indexOf(needle)
  if (at === -1) return null
  if (at === 0) return 0
  return haystack[at - 1] === ' ' ? 1 : 2
}

/** The three fields a query is matched against, best (and most Spanish) first. */
const HAYSTACKS: ((exercise: CatalogExercise) => string)[] = [
  (e) => e.name,
  (e) => e.nameEn,
  (e) => e.id,
]

/** Combines *where* it matched with *what* it matched, so a name hit always beats an id hit. */
function score(exercise: CatalogExercise, needle: string): number | null {
  let best: number | null = null
  HAYSTACKS.forEach((of, field) => {
    const rank = rankIn(fold(of(exercise)), needle)
    if (rank === null) return
    const combined = rank * HAYSTACKS.length + field
    if (best === null || combined < best) best = combined
  })
  return best
}

export interface ExerciseQuery {
  /** Free text over the Spanish name, the English name and the slug. */
  q?: string
  /** Matches primary *or* secondary — "what does this move work" is not a strict question. */
  muscle?: string
  equipment?: string
  /** AND-combined: every tag must be present. */
  tags?: string[]
  bodyPart?: string
  category?: string
  /** No equipment at all. Not the same as `equipment` unset, which means "any". */
  bodyweightOnly?: boolean
  /** Default 20, hard-capped at `MAX_RESULTS` — this is a picker, not a dump. */
  limit?: number
}

export const DEFAULT_RESULTS = 20

/** Licence term 3, expressed as a number: no paging, no cursor, no way to walk the set. */
export const MAX_RESULTS = 50

/**
 * The one search. Facets AND-combine with each other and with the text; results are ranked
 * by where the text matched and tie-broken by Spanish collation, so an empty query with a
 * facet on it reads as an alphabetical browse.
 */
export function searchExercises(query: ExerciseQuery = {}): CatalogExercise[] {
  const needle = query.q ? fold(query.q) : ''
  const limit = Math.min(Math.max(query.limit ?? DEFAULT_RESULTS, 1), MAX_RESULTS)

  const hits: { exercise: CatalogExercise; score: number }[] = []
  for (const exercise of EXERCISES) {
    if (query.bodyweightOnly && exercise.equipment !== null) continue
    if (query.equipment && exercise.equipment !== query.equipment) continue
    if (query.bodyPart && exercise.bodyPart !== query.bodyPart) continue
    if (query.category && exercise.category !== query.category) continue
    if (
      query.muscle &&
      !exercise.primaryMuscles.includes(query.muscle) &&
      !exercise.secondaryMuscles.includes(query.muscle)
    ) {
      continue
    }
    if (query.tags?.length && !query.tags.every((tag) => exercise.tags.includes(tag))) continue

    if (!needle) {
      hits.push({ exercise, score: 0 })
      continue
    }
    const matched = score(exercise, needle)
    if (matched !== null) hits.push({ exercise, score: matched })
  }

  hits.sort((a, b) => a.score - b.score || a.exercise.name.localeCompare(b.exercise.name, 'es'))
  return hits.slice(0, limit).map((hit) => hit.exercise)
}

/**
 * Which prescribed entries name an id this catalogue does not know.
 *
 * The write boundary's check, and it returns *which* rather than *whether* so the caller
 * can name the offending index — Spanish over HTTP, an English `ToolError` over MCP. An
 * entry with `exerciseId: null` is not an error and never appears here: a move the
 * catalogue does not have is a move the physio named, and the prescription still renders
 * from its own `name`.
 */
export function unknownExerciseIds(
  entries: readonly { exerciseId: string | null }[],
): { index: number; exerciseId: string }[] {
  const unknown: { index: number; exerciseId: string }[] = []
  entries.forEach((entry, index) => {
    if (entry.exerciseId != null && !BY_ID.has(entry.exerciseId)) {
      unknown.push({ index, exerciseId: entry.exerciseId })
    }
  })
  return unknown
}

/**
 * `card` is the pose the UI asks for when it does not know which poses exist.
 *
 * It cannot know: a session's payload carries an id and a Spanish name, never a pose list,
 * and shipping one would be a third copy of the catalogue. So the alias is resolved here,
 * on the server, against the row — the peak of a movement is the frame that reads as the
 * exercise, and a hold has only its one `main`. Returns `null` for a pose this exercise
 * does not have, which is what makes the image route unable to probe arbitrary keys.
 */
export function resolvePose(exercise: CatalogExercise, pose: string): string | null {
  if (pose === 'card') {
    return exercise.poses.includes('peak') ? 'peak' : (exercise.poses[0] ?? null)
  }
  return exercise.poses.includes(pose) ? pose : null
}

/**
 * The R2 key for one illustration.
 *
 * Keyed by **exercise id and pose, never by the source path**: twelve source files are
 * shared between variation aliases in RepDB's own tree, so a path is not an identity — two
 * exercises would collide on one key and the UI would key its rows by a shared string.
 * Uploading those twelve twice costs ~196 KB and buys an id that means one thing.
 *
 * The version segment is the avatar lesson generalised (`src/lib/avatar.ts`): bytes under
 * a successful URL never change, so a year-long immutable cache on them is honest, and a
 * re-vendored catalogue moves every URL at once instead of overwriting objects a browser
 * has already promised itself it need not re-fetch.
 */
export const exerciseImageKey = (id: string, pose: string): string =>
  `exercises/${CATALOG_VERSION}/${id}/${pose}.webp`
