import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  BODY_PARTS,
  CATALOG_SOURCE_SHA256,
  CATALOG_VERSION,
  CATEGORIES,
  DIFFICULTIES,
  EQUIPMENT,
  EXERCISES,
  MAX_RESULTS,
  MUSCLES,
  TAGS,
  exerciseById,
  exerciseImageKey,
  resolvePose,
  searchExercises,
  unknownExerciseIds,
} from '@/lib/exercises/catalog'
import {
  BODY_PART_LABELS,
  CATEGORY_LABELS,
  DIFFICULTY_LABELS,
  EQUIPMENT_LABELS,
  MUSCLE_LABELS,
  TAG_LABELS,
  equipmentLabel,
  muscleLabel,
} from '@/lib/exercise-labels'
import { CATALOG_COUNT, CATALOG_VERSION as META_VERSION, exerciseImageUrl } from '@/lib/exercise-meta'
import { BUILTIN_TEMPLATES } from '@/lib/starters'
import { GET as GET_SEARCH } from '@/pages/api/exercises'
import { GET as GET_ONE } from '@/pages/api/exercises/[id]'

/**
 * The vendored exercise catalogue, and the three joins nothing else can check.
 *
 * `catalog.json` is generated by `scripts/exercises-prune.mjs` from a third-party dataset
 * that moves a few times a year. What matters is not any particular number in it — pinning
 * those is the mistake `sw.test.ts` documents, where a correct change looks like six
 * regressions — but that the pieces around it still agree with each other:
 *
 *   1. the generated module and the generated JSON carry the same generation stamp;
 *   2. every facet slug the catalogue can render has a Spanish label;
 *   3. nothing that ships to the browser imports the 650 KB of prose.
 *
 * All three are invisible to `tsc` and all three fail on somebody's phone rather than in
 * CI if they are not asserted here.
 */

describe('exercise catalogue · integrity', () => {
  it('ships a plausible catalogue rather than a truncated download', () => {
    // Floors and shapes, never exact values: a refresh that adds ten exercises is a
    // correct change and must not read as a regression.
    expect(EXERCISES.length).toBeGreaterThanOrEqual(400)
    expect(CATALOG_VERSION).toMatch(/^[0-9a-f]{8}$/)
    expect(CATALOG_SOURCE_SHA256).toMatch(/^[0-9a-f]{64}$/)
  })

  it('keeps the generated browser module in step with the generated JSON', () => {
    // Two files, one generator, one run — and the version is what keys every image URL, so
    // a half-applied regeneration would point the whole UI at a generation R2 does not have.
    expect(META_VERSION).toBe(CATALOG_VERSION)
    expect(CATALOG_COUNT).toBe(EXERCISES.length)
  })

  it('gives every record the uniform shape the projection promises', () => {
    for (const exercise of EXERCISES) {
      expect(exercise.id).toMatch(/^[a-z0-9-]+$/)
      expect(exercise.name.length).toBeGreaterThan(0)
      expect(exercise.nameEn.length).toBeGreaterThan(0)
      expect(exercise.instructions.length).toBeGreaterThan(0)
      // Explicit, never absent — `undefined` where `null` was meant is the whole reason the
      // prune script writes these out rather than omitting them.
      expect(exercise.equipment === null || typeof exercise.equipment === 'string').toBe(true)
      expect(Array.isArray(exercise.tags)).toBe(true)
      expect(Array.isArray(exercise.secondaryMuscles)).toBe(true)
      expect(exercise.poses.length).toBeGreaterThan(0)
    }
  })

  it('carries only the two documented image shapes', () => {
    // `{start, peak}` for a movement, `{main}` for a hold. The UI branches on nothing else,
    // and `resolvePose` would silently answer null for a third shape.
    const shapes = new Set(EXERCISES.map((exercise) => exercise.poses.join('+')))
    expect([...shapes].sort()).toEqual(['main', 'start+peak'])
  })

  it('drops the languages and the columns the app does not read', () => {
    // The cut is most of the point: 2.1 MB of trilingual prose down to ~650 KB. A refresh
    // that quietly reinstated `_de` would be 1.4 MB riding into the Worker unnoticed.
    const raw = readFileSync(new URL('../../src/lib/exercises/catalog.json', import.meta.url), 'utf8')
    for (const dropped of ['name_de', 'description_en', 'instructions_de', '"met"', '"goals"']) {
      expect(raw).not.toContain(dropped)
    }
    expect(EXERCISES.some((exercise) => exercise.category === 'cardio')).toBe(false)
    expect(EXERCISES.some((exercise) => exercise.category === 'olympic')).toBe(false)
  })
})

describe('exercise catalogue · search', () => {
  it('finds a Spanish name without its accents and without its case', () => {
    const hits = searchExercises({ q: 'sentadilla' })
    expect(hits.length).toBeGreaterThan(0)
    expect(hits.every((hit) => hit.name.toLowerCase().includes('sentadilla'))).toBe(true)
  })

  it('finds a slug typed as words, which is how an English query arrives', () => {
    // `side-plank` and "side plank" are the same question. Folding every run of
    // non-alphanumerics to one space is what makes the slug, the English name and the
    // Spanish name one alphabet.
    const ids = searchExercises({ q: 'side plank' }).map((hit) => hit.id)
    expect(ids).toContain('side-plank')
  })

  it('matches the English name an agent would use', () => {
    const ids = searchExercises({ q: 'glute bridge' }).map((hit) => hit.id)
    expect(ids).toContain('glute-bridge')
  })

  it('puts the exact name first rather than whatever matched alphabetically', () => {
    const [first] = searchExercises({ q: 'plancha' })
    expect(first?.name.toLowerCase().startsWith('plancha')).toBe(true)
  })

  it('AND-combines facets with each other and with the text', () => {
    const kneeSafeBodyweight = searchExercises({ tags: ['knee_safe'], bodyweightOnly: true, limit: 50 })
    expect(kneeSafeBodyweight.length).toBeGreaterThan(0)
    for (const hit of kneeSafeBodyweight) {
      expect(hit.tags).toContain('knee_safe')
      expect(hit.equipment).toBeNull()
    }
  })

  it('counts a secondary muscle as a match, because "what does this work" is not strict', () => {
    const hits = searchExercises({ muscle: 'gluteus_medius', limit: 50 })
    expect(hits.length).toBeGreaterThan(0)
    expect(
      hits.every(
        (hit) =>
          hit.primaryMuscles.includes('gluteus_medius') || hit.secondaryMuscles.includes('gluteus_medius'),
      ),
    ).toBe(true)
  })

  it('browses alphabetically when a facet is given with no text at all', () => {
    const hits = searchExercises({ category: 'stretching', limit: 5 })
    const names = hits.map((hit) => hit.name)
    expect(names).toEqual([...names].sort((a, b) => a.localeCompare(b, 'es')))
  })

  it('never returns more than the cap, whatever it is asked for', () => {
    // Licence term 3 expressed as a number: there is no request that walks the set.
    expect(searchExercises({ q: 'a', limit: 5000 }).length).toBeLessThanOrEqual(MAX_RESULTS)
  })

  it('answers nothing for a query nothing matches', () => {
    expect(searchExercises({ q: 'zzzzznotanexercise' })).toEqual([])
  })
})

describe('exercise catalogue · the write boundary', () => {
  it('names which entry carries an id the catalogue does not know', () => {
    const unknown = unknownExerciseIds([
      { exerciseId: 'plank' },
      { exerciseId: 'no-such-move' },
      { exerciseId: null },
    ])
    expect(unknown).toEqual([{ index: 1, exerciseId: 'no-such-move' }])
  })

  it('treats a written-in exercise as legitimate, never as an error', () => {
    // «almejas con banda» as the physio said it outranks whatever RepDB files it under.
    expect(unknownExerciseIds([{ exerciseId: null }, { exerciseId: null }])).toEqual([])
  })
})

describe('exercise catalogue · image keys', () => {
  const movement = EXERCISES.find((exercise) => exercise.poses.includes('peak'))!
  const hold = EXERCISES.find((exercise) => exercise.poses.join() === 'main')!

  it('resolves the card alias to the frame that reads as the exercise', () => {
    // The UI cannot know which poses exist — a session payload carries an id and a name —
    // so the alias is resolved here, against the row.
    expect(resolvePose(movement, 'card')).toBe('peak')
    expect(resolvePose(hold, 'card')).toBe('main')
  })

  it('refuses a pose the exercise does not have, so the route cannot probe R2', () => {
    expect(resolvePose(hold, 'peak')).toBeNull()
    expect(resolvePose(movement, 'main')).toBeNull()
    expect(resolvePose(movement, '../avatars/someone')).toBeNull()
  })

  it('keys by exercise id and pose, never by the source path', () => {
    // Twelve source files are shared between variation aliases in RepDB's own tree, so a
    // path is not an identity: two exercises would collide on one key.
    expect(exerciseImageKey('squat', 'peak')).toBe(`exercises/${CATALOG_VERSION}/squat/peak.webp`)
    expect(exerciseImageUrl('squat', 'peak')).toBe(`/api/exercises/img/${CATALOG_VERSION}/squat/peak.webp`)
    expect(exerciseImageUrl('squat')).toBe(`/api/exercises/img/${CATALOG_VERSION}/squat/card.webp`)
  })

  it('puts the generation in the key, which is what makes the immutable cache honest', () => {
    expect(exerciseImageKey('squat', 'peak')).toContain(CATALOG_VERSION)
    expect(exerciseImageUrl('squat')).toContain(CATALOG_VERSION)
  })

  it('keeps the exercise prefix clear of the avatar prefix in the shared bucket', () => {
    // One R2 bucket holds both. The namespaces cannot collide, and this is where that
    // stops being an assertion in a comment.
    expect(exerciseImageKey('squat', 'peak').startsWith('exercises/')).toBe(true)
    expect(exerciseImageKey('squat', 'peak').startsWith('avatars/')).toBe(false)
  })

  it('looks an exercise up by its id', () => {
    expect(exerciseById('squat')?.id).toBe('squat')
    expect(exerciseById('no-such-move')).toBeUndefined()
  })
})

describe('exercise catalogue · Spanish labels', () => {
  const complete = (
    what: string,
    slugs: string[],
    labels: Record<string, string>,
  ) => {
    it(`labels every ${what} the catalogue can render`, () => {
      // A RepDB release that mints a new slug fails here, loudly, rather than rendering a
      // blank chip on somebody's phone. The lookups still fall back to the slug — a red
      // test is the right place to find out, and a blank label is never right to render.
      const missing = slugs.filter((slug) => !labels[slug])
      expect(missing).toEqual([])
    })
  }

  complete('muscle', MUSCLES, MUSCLE_LABELS)
  complete('tag', TAGS, TAG_LABELS)
  complete('equipment', EQUIPMENT, EQUIPMENT_LABELS)
  complete('body part', BODY_PARTS, BODY_PART_LABELS)
  complete('category', CATEGORIES, CATEGORY_LABELS)
  complete('difficulty', DIFFICULTIES, DIFFICULTY_LABELS)

  it('answers «Sin material» for the moves that need none', () => {
    // `equipment: null` *is* bodyweight — the source's own flag, derived rather than
    // stored twice — so the label function takes the column as stored.
    expect(equipmentLabel(null)).toBe('Sin material')
    expect(equipmentLabel('loop_band')).toBe('Minibanda')
  })

  it('falls back to the slug rather than to a blank', () => {
    expect(muscleLabel('newly_minted_slug')).toBe('newly_minted_slug')
  })
})

/**
 * The two endpoints, called directly.
 *
 * Both are pure functions of their request — the catalogue is a module import and neither
 * touches a binding, a clock or D1 — so they run here in plain Node against a fabricated
 * context, the way `mcp.test.ts` runs the tool registry. What is being pinned is not the
 * search (that is above) but the *boundary*: what a malformed query gets back, and what
 * the response is allowed to contain.
 *
 * The image route is the one that cannot be reached this way: it imports
 * `cloudflare:workers` for the bucket. Everything about it that is decidable without R2 —
 * the pose alias, the refusal of a pose an exercise does not have, the key — is
 * `resolvePose` and `exerciseImageKey`, tested above.
 */
describe('exercise catalogue · GET /api/exercises', () => {
  const get = async (query: string) => {
    const response = await (GET_SEARCH as (context: { url: URL }) => Promise<Response> | Response)({
      url: new URL(`https://app.test/api/exercises${query}`),
    })
    return { status: response.status, body: (await response.json()) as Record<string, never> }
  }

  it('refuses a request with no text and no facet — it is a search box, not a dump', async () => {
    // Licence term 3, at the boundary. There is no request this endpoint answers with
    // "everything", and the refusal says what to do instead, in Spanish.
    const empty = await get('')
    expect(empty.status).toBe(400)
    expect(String(empty.body.error)).toContain('Afina la búsqueda')

    // One letter matches a third of the catalogue and answers no question anyone asked.
    expect((await get('?q=p')).status).toBe(400)
  })

  it('accepts a facet on its own, which is how the picker chips work', async () => {
    const chip = await get('?bodyweight=1')
    expect(chip.status).toBe(200)
    expect(Array.isArray(chip.body.results)).toBe(true)
  })

  it('names the field when a facet value is not one the catalogue has', async () => {
    // A typo must not read as "there is no such exercise".
    const typo = await get('?muscle=glutes')
    expect(typo.status).toBe(400)
    expect(JSON.stringify(typo.body)).toContain('muscle')
  })

  it('returns trimmed rows and never the prose', async () => {
    const { body } = await get('?q=plancha')
    const results = body.results as unknown as Record<string, unknown>[]
    expect(results.length).toBeGreaterThan(0)
    for (const row of results) {
      expect(Object.keys(row).sort()).toEqual([
        'bodyPart',
        'category',
        'difficulty',
        'equipment',
        'id',
        'isUnilateral',
        'name',
      ])
    }
  })

  it('caps what it will hand back however large a limit is asked for', async () => {
    // 500 is refused rather than silently clamped, so a client asking for a dump is told.
    expect((await get('?q=pl&limit=500')).status).toBe(400)
    const capped = await get(`?q=pl&limit=${MAX_RESULTS}`)
    expect((capped.body.results as unknown as unknown[]).length).toBeLessThanOrEqual(MAX_RESULTS)
  })

  it('answers no-store, like every other endpoint that reads one athlete', async () => {
    const response = await (GET_SEARCH as (context: { url: URL }) => Promise<Response>)({
      url: new URL('https://app.test/api/exercises?q=plancha'),
    })
    expect(response.headers.get('cache-control')).toBe('no-store')
  })
})

describe('exercise catalogue · GET /api/exercises/[id]', () => {
  const get = async (id: string | undefined) =>
    (GET_ONE as (context: { params: { id?: string } }) => Promise<Response> | Response)({ params: { id } })

  it('answers one full record, prose included', async () => {
    const response = await get('plank')
    const body = (await response.json()) as Record<string, unknown>
    expect(response.status).toBe(200)
    expect(body.id).toBe('plank')
    expect(Array.isArray(body.instructions)).toBe(true)
    expect(typeof body.description).toBe('string')
  })

  it('404s an unknown slug in Spanish', async () => {
    const response = await get('no-such-move')
    expect(response.status).toBe(404)
    expect(String(((await response.json()) as { error: string }).error)).toBe('No existe ese ejercicio')
  })

  it('404s the bare img segment rather than falling through to R2', async () => {
    // `/api/exercises/img` is one segment and lands here; the four-segment image route is
    // its own file. Neither can be used to walk the other's namespace.
    expect((await get('img')).status).toBe(404)
  })
})

/**
 * The two built-in templates against the catalogue they were written from.
 *
 * `src/lib/starters.ts` is hand-written Spanish — nine knee-and-hip moves and eight core
 * ones — and every `exerciseId` in it was typed by a person reading a catalogue. Nothing
 * else joins the two: the templates are browser-safe and import no catalogue, precisely so
 * that they render with the catalogue nowhere in sight, which is also what would let a
 * dead id sit there quietly showing a broken tile.
 *
 * These assertions live here rather than beside `starters.ts` because this is the file
 * that already holds the catalogue, and because a re-vendor is exactly when they should
 * fail: an exercise RepDB renames is a template that has lost a picture.
 */
describe('exercise catalogue · the built-in templates', () => {
  const templates = BUILTIN_TEMPLATES

  it('names only ids the vendored catalogue actually has', () => {
    for (const template of templates) {
      expect(unknownExerciseIds(template.exercises), template.id).toEqual([])
    }
  })

  it('prescribes repetitions or seconds, never both and never neither', () => {
    // The same rule `plan-input.ts` refuses a write for. A built-in that broke it would be
    // storable by hand and unwritable through the API that copies it.
    for (const template of templates) {
      for (const exercise of template.exercises) {
        expect((exercise.reps == null) !== (exercise.durationS == null), `${template.id} · ${exercise.name}`).toBe(
          true,
        )
      }
    }
  })

  it('carries its own Spanish name for every move, so it renders with no catalogue', () => {
    for (const template of templates) {
      expect(template.exercises.length).toBeGreaterThan(0)
      for (const exercise of template.exercises) {
        expect(exercise.name.trim().length).toBeGreaterThan(0)
      }
    }
  })

  it('stays in the reserved id namespace that create/update/delete refuse', () => {
    for (const template of templates) expect(template.id.startsWith('treximo-')).toBe(true)
  })
})

/**
 * The boundary `tsc` cannot see.
 *
 * `src/lib/exercises/` parses to ~650 KB of Spanish prose. It belongs in the Worker and
 * nowhere else: one accidental import from a component and the whole catalogue rides into
 * a client bundle that is otherwise a few tens of KB, and nothing — not the type checker,
 * not the build, not a runtime error — would say so. This is the `nav.test.ts` shape:
 * read the source, and fail on the import.
 */
describe('exercise catalogue · the Worker-only boundary', () => {
  const dir = (path: string) => fileURLToPath(new URL(path, import.meta.url))

  /** Every file under a directory, recursively. */
  function sources(from: string): string[] {
    return readdirSync(from).flatMap((name) => {
      const path = `${from}/${name}`
      if (statSync(path).isDirectory()) return sources(path)
      return /\.(?:ts|tsx|astro)$/.test(name) ? [path] : []
    })
  }

  /** The browser-shipped modules outside `src/components/`, named one by one on purpose:
   *  a new one is a deliberate addition to this list, not something to be inferred. */
  const BROWSER_LIBS = [
    'strength.ts',
    'prescription.ts',
    'plan.ts',
    'workout.ts',
    'plan-client.ts',
    'starters.ts',
    'exercise-labels.ts',
    'exercise-meta.ts',
    'nav.ts',
    'format.ts',
    'paces.ts',
    'block.ts',
  ]

  it('names only modules that still exist, so the list cannot rot into a pass', () => {
    // A renamed file would otherwise drop silently out of the scan below and take its
    // guarantee with it.
    expect(BROWSER_LIBS.filter((name) => !existsSync(dir(`../../src/lib/${name}`)))).toEqual([])
  })

  it('is never imported by anything that ships to the browser', () => {
    const files = [
      ...sources(dir('../../src/components')),
      ...BROWSER_LIBS.map((name) => dir(`../../src/lib/${name}`)),
    ]

    const offenders: string[] = []
    for (const file of files) {
      for (const line of readFileSync(file, 'utf8').split('\n')) {
        if (!/from\s+['"][^'"]*lib\/exercises\/|from\s+['"]\.\/exercises\//.test(line)) continue
        // `import type` is erased at build, so naming the catalogue's record type costs
        // the bundle nothing — that is how `plan-client.ts` types a search hit.
        if (/^\s*import\s+type\b/.test(line)) continue
        offenders.push(`${file.split('/src/')[1]}: ${line.trim()}`)
      }
    }
    expect(offenders).toEqual([])
  })
})
